"""Renders the full financial health card from real Analytics/AI Engine output.

Nothing here computes or interprets data -- it only displays the scorecard
and report dicts exactly as generate_scorecard()/generate_report() produced
them, the same "engine does analysis, this layer only presents it" split
used throughout the rest of this project.
"""

from __future__ import annotations

import json
from typing import Any

import streamlit as st

from components.charts import render_chart_config

_DIMENSION_LABELS = {
    "aa_bank_cashflow": "AA Bank Cashflow",
    "gst_quality": "GST Quality",
    "upi_behaviour": "UPI Behaviour",
    "epfo_stability": "EPFO Stability",
    "compliance_bureau": "Compliance & Bureau",
}


def render_health_card(customer: dict[str, Any], scorecard: dict[str, Any], report: dict[str, Any]) -> None:
    col1, col2, col3 = st.columns([3, 2, 1])
    with col1:
        st.markdown(f"### {customer['business_name']}")
    with col2:
        st.caption(f"GST: {customer['gst_number']}")
    with col3:
        st.caption(f"Sector: {customer['sector']}")

    method = report["generation_method"]
    if method == "gemini":
        st.caption("Narrative generated by Gemini")
    else:
        st.caption("Narrative generated by deterministic fallback template (Gemini unavailable)")

    st.divider()

    gauge_config = next((c for c in report["chart_configs"] if c["type"] == "gauge"), None)
    col_gauge, col_summary = st.columns([2, 3])
    with col_gauge:
        if gauge_config:
            st.plotly_chart(render_chart_config(gauge_config), width='stretch')
    with col_summary:
        st.metric("Overall Health", scorecard["score_interpretation"], f"{scorecard['composite_score']}/100")
        st.write(f"**Assessment Date:** {scorecard['scorecard_date']}")

    st.divider()
    st.subheader("Financial Dimension Scores")
    dims = scorecard["dimension_scores"]
    cols = st.columns(len(dims))
    for col, (key, value) in zip(cols, dims.items()):
        col.metric(_DIMENSION_LABELS.get(key, key), f"{value}/100")

    st.divider()
    st.subheader("Financial Analysis")
    other_charts = [c for c in report["chart_configs"] if c["type"] != "gauge"]
    for i in range(0, len(other_charts), 2):
        row = other_charts[i : i + 2]
        cols = st.columns(len(row))
        for col, config in zip(cols, row):
            with col:
                st.plotly_chart(render_chart_config(config), width='stretch')

    st.divider()
    col_green, col_red = st.columns(2)
    with col_green:
        st.subheader("🟢 Strengths")
        if scorecard["green_flags"]:
            for flag in scorecard["green_flags"]:
                st.write(f"✅ {flag}")
        else:
            st.caption("None recorded")
    with col_red:
        st.subheader("🔴 Risks")
        if scorecard["red_flags"]:
            for flag in scorecard["red_flags"]:
                st.write(f"⚠️ {flag}")
        else:
            st.caption("None recorded")

    st.divider()
    st.subheader("Financial Assessment")
    narrative = report["narrative"]
    st.write(narrative["summary"])
    st.write(narrative["financial_health"])
    st.markdown("**Key strengths:**")
    for item in narrative["strengths"]:
        st.write(f"- {item}")
    st.markdown("**Key risks:**")
    for item in narrative["risks"]:
        st.write(f"- {item}")
    st.markdown("**Recommendations:**")
    st.write(narrative["recommendations"])

    audit = report["audit_trail"]
    st.caption(
        f"Data sources used: {', '.join(audit['data_sources_used'])} | "
        f"{audit['ratios_cited']} ratios cited | generated {report['generated_at']}"
    )

    st.divider()
    col_dl1, col_dl2 = st.columns(2)
    with col_dl1:
        st.download_button(
            "Download Report (JSON)",
            data=json.dumps(report, indent=2),
            file_name=f"report_{customer['customer_id']}_{scorecard['scorecard_date']}.json",
            mime="application/json",
            width='stretch',
        )
    with col_dl2:
        st.download_button(
            "Download Scorecard (JSON)",
            data=json.dumps(scorecard, indent=2),
            file_name=f"scorecard_{customer['customer_id']}_{scorecard['scorecard_date']}.json",
            mime="application/json",
            width='stretch',
        )
