"""Renders one combined PDF (scorecard + narrative) from the same scorecard/
report dicts components/cards.py displays on-screen -- a third, printable
presentation of data the Analytics/AI Engines already computed, nothing here
computes or interprets anything.

Chart images are produced by ai/render.py's Matplotlib renderer, the same
chart_configs contract components/charts.py renders with Plotly for the
on-screen version -- one data contract, now three renderers (interactive,
static-PNG-for-PDF, and this PDF layout on top of that PNG output).
"""

from __future__ import annotations

import io
import tempfile
from pathlib import Path
from typing import Any

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import cm
from reportlab.platypus import (
    Image,
    ListFlowable,
    ListItem,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from ai.render import render_chart_configs

_DIMENSION_LABELS = {
    "aa_bank_cashflow": "AA Bank Cashflow",
    "gst_quality": "GST Quality",
    "upi_behaviour": "UPI Behaviour",
    "epfo_stability": "EPFO Stability",
    "compliance_bureau": "Compliance & Bureau",
}


def _styles() -> dict[str, ParagraphStyle]:
    base = getSampleStyleSheet()
    return {
        "title": base["Title"],
        "heading": base["Heading2"],
        "body": base["BodyText"],
        "caption": ParagraphStyle("caption", parent=base["BodyText"], fontSize=8, textColor=colors.grey),
    }


def _dimension_table(dimension_scores: dict[str, int], styles: dict[str, ParagraphStyle]) -> Table:
    rows = [["Dimension", "Score"]] + [
        [_DIMENSION_LABELS.get(key, key), f"{value}/100"] for key, value in dimension_scores.items()
    ]
    table = Table(rows, colWidths=[10 * cm, 4 * cm])
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#4a90d9")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f2f2f2")]),
            ]
        )
    )
    return table


def _bullet_list(items: list[str], styles: dict[str, ParagraphStyle]) -> ListFlowable:
    return ListFlowable(
        [ListItem(Paragraph(item, styles["body"])) for item in items],
        bulletType="bullet",
    )


def build_pdf_report(customer: dict[str, Any], scorecard: dict[str, Any], report: dict[str, Any]) -> bytes:
    """Build the combined health card PDF and return its bytes."""
    styles = _styles()
    story: list[Any] = []

    story.append(Paragraph(customer["business_name"], styles["title"]))
    story.append(
        Paragraph(
            f"GST: {customer['gst_number']} &nbsp;|&nbsp; Sector: {customer['sector']}",
            styles["caption"],
        )
    )
    method_note = (
        "Narrative generated by Gemini"
        if report["generation_method"] == "gemini"
        else "Narrative generated by deterministic fallback template (Gemini unavailable)"
    )
    story.append(Paragraph(method_note, styles["caption"]))
    story.append(Spacer(1, 0.5 * cm))

    story.append(
        Paragraph(
            f"<b>Overall Health:</b> {scorecard['score_interpretation']} "
            f"({scorecard['composite_score']}/100) &nbsp;|&nbsp; "
            f"<b>Assessment Date:</b> {scorecard['scorecard_date']}",
            styles["body"],
        )
    )
    story.append(Spacer(1, 0.5 * cm))

    story.append(Paragraph("Financial Dimension Scores", styles["heading"]))
    story.append(_dimension_table(scorecard["dimension_scores"], styles))
    story.append(Spacer(1, 0.5 * cm))

    with tempfile.TemporaryDirectory() as tmp_dir:
        chart_paths = render_chart_configs(report["chart_configs"], tmp_dir)
        story.append(Paragraph("Financial Analysis", styles["heading"]))
        for path in chart_paths:
            story.append(Image(str(path), width=15 * cm, height=15 * cm * 0.55, kind="proportional"))
            story.append(Spacer(1, 0.3 * cm))

        story.append(Paragraph("Strengths & Risks", styles["heading"]))
        story.append(Paragraph("Strengths", styles["body"]))
        story.append(
            _bullet_list(scorecard["green_flags"], styles) if scorecard["green_flags"] else Paragraph("None recorded", styles["caption"])
        )
        story.append(Paragraph("Risks", styles["body"]))
        story.append(
            _bullet_list(scorecard["red_flags"], styles) if scorecard["red_flags"] else Paragraph("None recorded", styles["caption"])
        )
        story.append(Spacer(1, 0.5 * cm))

        narrative = report["narrative"]
        story.append(Paragraph("Financial Assessment", styles["heading"]))
        story.append(Paragraph(narrative["summary"], styles["body"]))
        story.append(Paragraph(narrative["financial_health"], styles["body"]))
        story.append(Paragraph("Key strengths:", styles["body"]))
        story.append(_bullet_list(narrative["strengths"], styles))
        story.append(Paragraph("Key risks:", styles["body"]))
        story.append(_bullet_list(narrative["risks"], styles))
        story.append(Paragraph("Recommendations:", styles["body"]))
        story.append(Paragraph(narrative["recommendations"], styles["body"]))
        story.append(Spacer(1, 0.5 * cm))

        audit = report["audit_trail"]
        story.append(
            Paragraph(
                f"Data sources used: {', '.join(audit['data_sources_used'])} | "
                f"{audit['ratios_cited']} ratios cited | generated {report['generated_at']}",
                styles["caption"],
            )
        )

        buffer = io.BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=A4, topMargin=1.5 * cm, bottomMargin=1.5 * cm)
        doc.build(story)  # must run inside the TemporaryDirectory block -- Image flowables read chart_paths lazily at build() time

    return buffer.getvalue()
